#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "shader-art"
version = "0.1.0"
authors = ["Zephyr Squall <145758512+ZephyrSquall@users.noreply.github.com>"]
description = "Gallery for Zephyr Squall's shader art"

[[trigger.http]]
route = "/..."
component = "shader-art"

[component.shader-art]
source = { url = "https://github.com/spinframework/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "dist", destination = "/" }]
